// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScaleApi.Data;

namespace ScaleApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220317182540_powerMeas")]
    partial class powerMeas
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.14");

            modelBuilder.Entity("ScaleApi.Models.Db.PowerMeasurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<float?>("ActualConsumption")
                        .HasColumnType("float");

                    b.Property<float?>("ActualProduction")
                        .HasColumnType("float");

                    b.Property<int?>("ActualTarrif")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReceivedTimestamp")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime");

                    b.Property<float?>("TotalConsumption1")
                        .HasColumnType("float");

                    b.Property<float?>("TotalConsumption2")
                        .HasColumnType("float");

                    b.Property<float?>("TotalGasConsumption")
                        .HasColumnType("float");

                    b.Property<float?>("TotalProduction1")
                        .HasColumnType("float");

                    b.Property<float?>("TotalProduction2")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("PowerMeasurements");
                });

            modelBuilder.Entity("ScaleApi.Models.Db.WeightMeasurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("MeasurementTimestamp")
                        .HasColumnType("datetime");

                    b.Property<int>("RawWeight")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReceivedTimestamp")
                        .HasColumnType("datetime");

                    b.Property<double>("Weight")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("Measurements");
                });
#pragma warning restore 612, 618
        }
    }
}
